# Generated by Django 3.0.4 on 2020-05-20 06:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_detail', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_details', to='cities.City')),
            ],
            options={
                'ordering': ('city',),
            },
        ),
    ]
